name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_push:
    runs_on: ubuntu_latest

    steps:
          - name: Checkout Code
            uses: actions/checkout@v4

          - name: Set up JDK 17
            uses: actions/setup-java@v3
            with:
              java-version: &#39;17&#39;
              distribution: &#39;temurin&#39;

          - name: Build with Maven
            run: mvn clean package -DskipTests

          - name: Log in to Docker Hub using CLI
            run: docker login -u sharmarakesh -p ${{ secrets.DOCKER_HUB_TOKEN }}

          - name: Build Docker Image
            run: |
              docker build -t sharmarakesh/violetapple-springboot-project:latest .

          - name: Push Docker Image to Docker Hub
            run: |
              docker push sharmarakesh/violetapple-springboot-project:latest